/* ==========================================================================
   NEXORA — Data Layer
   Everything the UI renders is driven from these structures. Edit here,
   nothing else, to add real content later.
   ========================================================================== */

const NEXORA_DATA = {

  drive: {
    pdf: "https://drive.google.com/drive/folders/1hQQ5s9Pu1ibDKDUYU2cb555qbXZdJqWZ?usp=drive_link",
    doc: "https://drive.google.com/drive/folders/1BISmcwYOLl3op18dgXSpZ6DiUsYR5k0T?usp=drive_link",
    code: "https://drive.google.com/drive/folders/1Cs4HoianSon-55zcPWta4gmqudGUroXT?usp=drive_link",
    image: "https://drive.google.com/drive/folders/1ZJYKMHLf7bGQGM_tzfW-h10XBvtomycD?usp=drive_link",
    all: "https://drive.google.com/drive/folders/YOUR_ROOT_FOLDER_ID"
  },

  subjects: [
    { id: "webdev", name: "Web Development", icon: "code-2", progress: 75, resources: 22 },
    { id: "dbms", name: "DBMS", icon: "database", progress: 70, resources: 20 },
    { id: "aspnet", name: "ASP.NET", icon: "globe", progress: 60, resources: 9 },
    { id: "java", name: "Java", icon: "coffee", progress: 40, resources: 4 },
    { id: "c-lang", name: "C Language", icon: "terminal", progress: 50, resources: 4 },
    { id: "cloud", name: "Cloud Computing", icon: "cloud", progress: 22, resources: 3 },
    { id: "python", name: "Python", icon: "terminal", progress: 65, resources: 1 },
    { id: "aiml", name: "AI / ML", icon: "brain-circuit", progress: 30, resources: 2 },
    { id: "php", name: "PHP", icon: "file-code", progress: 45, resources: 2 },
    { id: "android", name: "Android", icon: "smartphone", progress: 50, resources: 2 },
    { id: "os", name: "Operating Systems", icon: "cpu", progress: 48, resources: 1 },
    { id: "arch", name: "Computer Architecture", icon: "layers", progress: 35, resources: 1 },
    { id: "iks", name: "IKS", icon: "book", progress: 40, resources: 1 },
    { id: "admin", name: "Admin", icon: "settings", progress: 80, resources: 1 },
    { id: "general", name: "General / Exams", icon: "folder", progress: 90, resources: 17 }
],

  projects: [
    {
      id: "nexora",
      name: "Nexora",
      description: "Personal knowledge and project hub — the OS this page is running.",
      category: "Web",
      tech: ["JavaScript", "HTML", "CSS", "CDN"],
      status: "active",
      updated: "2 days ago",
      github: "https://github.com/kishan741i/NEXORA",
      demo: "",
    },
    {
      id: "drivelink",
      name: "DriveLink",
      description: "Cloud file management and sharing tool inspired by Google Drive architecture.",
      category: "Cloud",
      tech: ["JavaScript", "HTML", "CSS"],
      status: "live",
      updated: "Recent",
      github: "https://github.com/kishan741i/DriveLink",
      demo: "https://kishan741i.github.io/DriveLink",
    },
    {
      id: "3dmodel",
      name: "3DModel",
      description: "Interactive 3D model viewer and renderer built for the web.",
      category: "Graphics",
      tech: ["JavaScript", "WebGL", "Three.js" "HTML", "CSS"],
      status: "live",
      updated: "Recent",
      github: "https://github.com/kishan741i/3d-model",
      demo: "https://kishan741i.github.io/3d-model",
    },
    {
      id: "habit-tracker-pro",
      name: "Habit Tracker Pro",
      description: "Advanced daily habit builder and streak consistency tracker.",
      category: "Productivity",
      tech: ["JavaScript", "Tailwind CSS", "HTML5"],
      status: "live",
      updated: "Recent",
      github: "https://github.com/kishan741i/Habit-Tracker-Pro",
      demo: "https://kishan741i.github.io/Habit-tracker-Pro/",
    },
    {
      id: "career-navigator",
      name: "Career Navigator",
      description: "Guidance portal and roadmap tool for student career planning.",
      category: "Education",
      tech: ["HTML", "CSS", "JavaScript"],
      status: "archived",
      updated: "Months ago",
      github: "https://github.com/kishan741i/Career-Navigator",
      demo: "https://kishan741i.github.io/career-navigator",
    },
    {
      id: "notes-app",
      name: "Notes App",
      description: "Minimalist note-taking application with local storage support.",
      category: "Productivity",
      tech: ["PHP", "HTML", "CDN", "CSS", "JavaScript", "MySQL"],
      status: "development",
      updated: "In progress",
      github: "https://github.com/kishan741i/notes_app/tree/master",
      demo: "",
    },
    {
      id: "news-site",
      name: "News Site",
      description: "Dynamic news aggregator fetching daily headlines and articles.",
      category: "Web",
      tech: ["PHP", "HTML", "CDN", "CSS", "JavaScript", "MySQL"],
      status: "development",
      updated: "In progress",
      github: "https://github.com/kishan741i/news-site/tree/master",
      demo: "",
    }
  ],

  library : [
    { id: 1, name: "DBMS Draft", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 2, name: "DBMS Output", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 3, name: "DBMS PL-SQL", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 4, name: "DBMS Practical", category: "code", type: "PPT", subject: "DBMS", semester: "3" },
    { id: 5, name: "DBMS SQL Sequence", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 6, name: "DBMS SQL View", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 7, name: "DBMS SQL", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 8, name: "Python AI ML Unit 3 Topic 4 Content Provider Complete Presentation", category: "code", type: "PPT", subject: "AI / ML", semester: "6" },
    { id: 9, name: "Python", category: "code", type: "ZIP", subject: "Python", semester: "2" },
    { id: 10, name: "Supervisor List BCA 2025-26", category: "spreadsheet", type: "XLSX", subject: "BCA", semester: "6" },
    { id: 11, name: "C Language Programs", category: "doc", type: "DOC", subject: "C Language", semester: "1" },
    { id: 12, name: "Completion Certificate BBA", category: "doc", type: "DOC", subject: "BBA", semester: "6" },
    { id: 13, name: "DBMS PL-SQL Copy Paste Password Asus 8", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 14, name: "DBMS PL-SQL", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 15, name: "DBMS PL-SQL", category: "doc", type: "TXT", subject: "DBMS", semester: "3" },
    { id: 16, name: "DBMS SQL", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 17, name: "DBMS SQL", category: "doc", type: "TXT", subject: "DBMS", semester: "3" },
    { id: 18, name: "DBMS Tables", category: "doc", type: "TXT", subject: "DBMS", semester: "3" },
    { id: 19, name: "DBMS Unit 3", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 20, name: "DBMS Unit 4", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 21, name: "For Nodel Officer", category: "doc", type: "DOC", subject: "General", semester: "6" },
    { id: 22, name: "Java ActionListener", category: "doc", type: "DOC", subject: "Java", semester: "4" },
    { id: 23, name: "Java Adapter Class", category: "doc", type: "DOC", subject: "Java", semester: "4" },
    { id: 24, name: "Java Layout Manager", category: "doc", type: "DOC", subject: "Java", semester: "4" },
    { id: 25, name: "Operating System OS Question Bank", category: "doc", type: "DOC", subject: "Operating Systems", semester: "4" },
    { id: 26, name: "Web Development CSS Material Final", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 27, name: "Web Development HTML", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 28, name: "Web Development JavaScript Builtin Function Array", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 29, name: "Web Development JavaScript New Material", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 30, name: "Web Development Unit 5", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 31, name: "ASP.NET Image 20250614 WA0000", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 32, name: "ASP.NET Image 20250614 WA0001", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 33, name: "ASP.NET Image 20250614 WA0002", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 34, name: "ASP.NET Image 20250614 WA0003", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 35, name: "ASP.NET Image 20250715 WA0002", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 36, name: "ASP.NET Image 20250715 WA0003", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 37, name: "ASP.NET Image 20250909 WA0000", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 38, name: "ASP.NET Image 20250911 WA0039", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 39, name: "DBMS WhatsApp Image 2025-03-26 at 7.01.37 AM (1)", category: "image", type: "JPEG", subject: "DBMS", semester: "3" },
    { id: 40, name: "DBMS WhatsApp Image 2025-03-26 at 7.01.37 AM", category: "image", type: "JPEG", subject: "DBMS", semester: "3" },
    { id: 41, name: "Android Syllabus", category: "pdf", type: "PDF", subject: "Android", semester: "6" },
    { id: 42, name: "Android Ripal Pandya", category: "pdf", type: "PDF", subject: "Android", semester: "6" },
    { id: 43, name: "ASP.NET Practical", category: "pdf", type: "PDF", subject: "ASP.NET", semester: "6" },
    { id: 44, name: "C Language Programme File Definition", category: "pdf", type: "PDF", subject: "C Language", semester: "1" },
    { id: 45, name: "C Language HP", category: "pdf", type: "PDF", subject: "C Language", semester: "1" },
    { id: 46, name: "C Language KM", category: "pdf", type: "PDF", subject: "C Language", semester: "1" },
    { id: 47, name: "Cloud Computing Notes", category: "pdf", type: "PDF", subject: "Cloud Computing", semester: "6" },
    { id: 48, name: "Cloud Computing Unit 01", category: "pdf", type: "PDF", subject: "Cloud Computing", semester: "6" },
    { id: 49, name: "Cloud Computing Unit 02", category: "pdf", type: "PDF", subject: "Cloud Computing", semester: "6" },
    { id: 50, name: "Computer Organization and Architecture", category: "pdf", type: "PDF", subject: "Computer Architecture", semester: "3" },
    { id: 51, name: "DBMS 1", category: "pdf", type: "PDF", subject: "DBMS", semester: "3" },
    { id: 52, name: "DBMS 2", category: "pdf", type: "PDF", subject: "DBMS", semester: "3" },
    { id: 53, name: "IKS Ethics Values", category: "pdf", type: "PDF", subject: "IKS", semester: "1" },
    { id: 54, name: "Java JS 2", category: "pdf", type: "PDF", subject: "Java", semester: "4" },
    { id: 55, name: "Java Practical", category: "pdf", type: "PDF", subject: "Java", semester: "4" },
    { id: 56, name: "PHP Practical", category: "pdf", type: "PDF", subject: "PHP", semester: "6" },
    { id: 57, name: "PHP Theory", category: "pdf", type: "PDF", subject: "PHP", semester: "6" },
    { id: 58, name: "Python AI ML Unit 3 Master Upto Topic 3", category: "pdf", type: "PDF", subject: "AI / ML", semester: "6" },
    { id: 59, name: "React JS Semester 6", category: "pdf", type: "PDF", subject: "Web Development", semester: "6" },
    { id: 60, name: "Semester 1 Assignment", category: "pdf", type: "PDF", subject: "General", semester: "1" },
    { id: 61, name: "Semester 1 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "1" },
    { id: 62, name: "Semester 1 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "1" },
    { id: 63, name: "Semester 1 LEB File", category: "pdf", type: "PDF", subject: "General", semester: "1" },
    { id: 64, name: "Semester 2 Assignment", category: "pdf", type: "PDF", subject: "General", semester: "2" },
    { id: 65, name: "Semester 2 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "2" },
    { id: 66, name: "Semester 2 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "2" },
    { id: 67, name: "Semester 3 Assignment", category: "pdf", type: "PDF", subject: "General", semester: "3" },
    { id: 68, name: "Semester 3 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "3" },
    { id: 69, name: "Semester 3 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "3" },
    { id: 70, name: "Semester 4 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "4" },
    { id: 71, name: "Semester 4 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "4" },
    { id: 72, name: "Semester 5 Assignment", category: "pdf", type: "PDF", subject: "General", semester: "5" },
    { id: 73, name: "Semester 5 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "5" },
    { id: 74, name: "Semester 5 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "5" },
    { id: 75, name: "Semester 5 LEB File", category: "pdf", type: "PDF", subject: "General", semester: "5" },
    { id: 76, name: "Semester 6 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "6" },
    { id: 77, name: "Web Development HTML Mayur Sir", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 78, name: "Web Development Chapter 4-5", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 79, name: "Web Development CSS Material", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 80, name: "Web Development FY Exam", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 81, name: "Web Development Microsoft PowerPoint Basics", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 82, name: "Web Development Networking", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 83, name: "Web Development Share Unit 1 Basics of HTML Ripal Pandya", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 84, name: "Web Development Unit 3", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 85, name: "Web Development Word 1", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 86, name: "Web Development Word Shortcuts", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" }
  ],
 

  quickLinks: [
    { name: "MDN Web Docs", description: "Web platform reference and guides", url: "https://developer.mozilla.org", icon: "book-open" },
    { name: "W3Schools", description: "Quick syntax and examples", url: "https://www.w3schools.com", icon: "graduation-cap" },
    { name: "GeeksforGeeks", description: "DSA and CS fundamentals", url: "https://www.geeksforgeeks.org", icon: "brain" },
    { name: "QuickRef.me", description: "Cheat sheets for everything", url: "https://quickref.me", icon: "zap" },
    { name: "OverAPI", description: "Collected cheat sheets", url: "https://overapi.com", icon: "layout-list" },
    { name: "DevDocs", description: "Offline-first API documentation", url: "https://devdocs.io", icon: "file-code" },
  ],

  discoveries: [
    { title: "Quantum Computing", description: "A gentle overview of qubits, superposition and why quantum machines could change computation.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Quantum_computing", category: "Science" },
    { title: "The Internet Archive", description: "Millions of free books, software, music and websites — a library of the entire web.", source: "Internet Archive", url: "https://archive.org", category: "Library" },
    { title: "OpenStreetMap", description: "A free, editable map of the world built by volunteers everywhere.", source: "OpenStreetMap", url: "https://www.openstreetmap.org", category: "Maps" },
    { title: "CSS Grid Garden", description: "Learn CSS grid by playing a small puzzle game about growing a garden.", source: "CSS Grid Garden", url: "https://cssgridgarden.com", category: "Learning" },
    { title: "Explorable Explanations", description: "Interactive essays that let you play with the concept instead of just reading about it.", source: "explorabl.es", url: "https://explorabl.es", category: "Interactive" },
    { title: "The Paris Review", description: "Long-form interviews and writing on craft from working authors.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/The_Paris_Review", category: "Culture" },
    { title: "Neural Networks, Visually", description: "A visual, intuitive introduction to how neural networks actually learn.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Artificial_neural_network", category: "AI / ML" },
    { title: "Undersea Cables Map", description: "A live map of the physical cables that carry the entire internet across oceans.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Submarine_communications_cable", category: "Infrastructure" },
  ],

  activities: [
    { text: "New resource added to DBMS", time: "2h ago" },
    { text: "Nexora project updated", time: "6h ago" },
    { text: "Library reorganized — 87 files", time: "2d ago" },
    { text: "New discovery: Explorable Explanations", time: "3d ago" },
    { text: "System maintenance completed", time: "5d ago" },
  ],

  stats: {
    visitors: 1248,
    projects: 6,
    documents: 115,
    version: "v8.0",
  },

  notice: {
    active: true,
    title: "System Notice",
    text: "We are actively improving this web & app. Stay tuned for new updates.",
  },
};
