/* ==========================================================================
   NEXORA — Data Layer
   Everything the UI renders is driven from these structures. Edit here,
   nothing else, to add real content later.
   ========================================================================== */

const NEXORA_DATA = {

  drive: {
    pdf: "https://drive.google.com/drive/folders/1hQQ5s9Pu1ibDKDUYU2cb555qbXZdJqWZ?usp=drive_link",
    doc: "https://drive.google.com/drive/folders/1BISmcwYOLl3op18dgXSpZ6DiUsYR5k0T?usp=drive_link",
    code: "https://drive.google.com/drive/folders/1Cs4HoianSon-55zcPWta4gmqudGUroXT?usp=drive_link",
    image: "https://drive.google.com/drive/folders/1ZJYKMHLf7bGQGM_tzfW-h10XBvtomycD?usp=drive_link",
    all: "https://drive.google.com/drive/folders/YOUR_ROOT_FOLDER_ID"
  },

  subjects: [
    { id: "webdev", name: "Web Development", icon: "code-2", progress: 75, resources: 22 },
    { id: "dbms", name: "DBMS", icon: "database", progress: 70, resources: 20 },
    { id: "aspnet", name: "ASP.NET", icon: "globe", progress: 60, resources: 9 },
    { id: "java", name: "Java", icon: "coffee", progress: 40, resources: 4 },
    { id: "c-lang", name: "C Language", icon: "terminal", progress: 50, resources: 4 },
    { id: "cloud", name: "Cloud Computing", icon: "cloud", progress: 22, resources: 3 },
    { id: "python", name: "Python", icon: "terminal", progress: 65, resources: 1 },
    { id: "aiml", name: "AI / ML", icon: "brain-circuit", progress: 30, resources: 2 },
    { id: "php", name: "PHP", icon: "file-code", progress: 45, resources: 2 },
    { id: "android", name: "Android", icon: "smartphone", progress: 50, resources: 2 },
    { id: "os", name: "Operating Systems", icon: "cpu", progress: 48, resources: 1 },
    { id: "arch", name: "Computer Architecture", icon: "layers", progress: 35, resources: 1 },
    { id: "iks", name: "IKS", icon: "book", progress: 40, resources: 1 },
    { id: "admin", name: "Admin", icon: "settings", progress: 80, resources: 1 },
    { id: "general", name: "General / Exams", icon: "folder", progress: 90, resources: 17 }
],

  projects: [
    {
      id: "nexora",
      name: "Nexora",
      description: "Personal knowledge and project hub — the OS this page is running.",
      category: "Web",
      tech: ["JavaScript", "HTML", "CSS", "CDN"],
      status: "active",
      updated: "2 days ago",
      github: "https://github.com/kishan741i/NEXORA",
      demo: "",
    },
    {
      id: "drivelink",
      name: "DriveLink",
      description: "Cloud file management and sharing tool inspired by Google Drive architecture.",
      category: "Cloud",
      tech: ["JavaScript", "HTML", "CSS"],
      status: "live",
      updated: "Recent",
      github: "https://github.com/kishan741i/DriveLink",
      demo: "https://kishan741i.github.io/DriveLink",
    },
    {
      id: "3dmodel",
      name: "3DModel",
      description: "Interactive 3D model viewer and renderer built for the web.",
      category: "Graphics",
      tech: ["JavaScript", "WebGL", "Three.js", "HTML", "CSS"],
      status: "live",
      updated: "Recent",
      github: "https://github.com/kishan741i/3d-model",
      demo: "https://kishan741i.github.io/3d-model",
    },
    {
      id: "habit-tracker-pro",
      name: "Habit Tracker Pro",
      description: "Advanced daily habit builder and streak consistency tracker.",
      category: "Productivity",
      tech: ["JavaScript", "Tailwind CSS", "HTML5"],
      status: "live",
      updated: "Recent",
      github: "https://github.com/kishan741i/Habit-Tracker-Pro",
      demo: "https://kishan741i.github.io/Habit-tracker-Pro/",
    },
    {
      id: "career-navigator",
      name: "Career Navigator",
      description: "Guidance portal and roadmap tool for student career planning.",
      category: "Education",
      tech: ["HTML", "CSS", "JavaScript"],
      status: "archived",
      updated: "Months ago",
      github: "https://github.com/kishan741i/Career-Navigator",
      demo: "https://kishan741i.github.io/career-navigator",
    },
    {
      id: "notes-app",
      name: "Notes App",
      description: "Minimalist note-taking application with local storage support.",
      category: "Productivity",
      tech: ["PHP", "Bootstrap", "CSS", "JavaScript", "MySQL"],
      status: "development",
      updated: "In progress",
      github: "https://github.com/kishan741i/notes_app/tree/master",
      demo: "",
    },
    {
      id: "news-site",
      name: "News Site",
      description: "Dynamic news aggregator fetching daily headlines and articles.",
      category: "Web",
      tech: ["PHP", "Bootstrap", "CSS", "JavaScript", "MySQL"],
      status: "development",
      updated: "In progress",
      github: "https://github.com/kishan741i/news-site/tree/master",
      demo: "",
    }
  ],

  library : [
    { id: 1, name: "DBMS Draft", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 2, name: "DBMS Output", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 3, name: "DBMS PL-SQL", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 4, name: "DBMS Practical", category: "code", type: "PPT", subject: "DBMS", semester: "3" },
    { id: 5, name: "DBMS SQL Sequence", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 6, name: "DBMS SQL View", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 7, name: "DBMS SQL", category: "code", type: "SQL", subject: "DBMS", semester: "3" },
    { id: 8, name: "Python AI ML Unit 3 Topic 4 Content Provider Complete Presentation", category: "code", type: "PPT", subject: "AI / ML", semester: "6" },
    { id: 9, name: "Python", category: "code", type: "ZIP", subject: "Python", semester: "2" },
    { id: 10, name: "Supervisor List BCA 2025-26", category: "spreadsheet", type: "XLSX", subject: "BCA", semester: "6" },
    { id: 11, name: "C Language Programs", category: "doc", type: "DOC", subject: "C Language", semester: "1" },
    { id: 12, name: "Completion Certificate BBA", category: "doc", type: "DOC", subject: "BBA", semester: "6" },
    { id: 13, name: "DBMS PL-SQL Copy Paste Password Asus 8", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 14, name: "DBMS PL-SQL", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 15, name: "DBMS PL-SQL", category: "doc", type: "TXT", subject: "DBMS", semester: "3" },
    { id: 16, name: "DBMS SQL", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 17, name: "DBMS SQL", category: "doc", type: "TXT", subject: "DBMS", semester: "3" },
    { id: 18, name: "DBMS Tables", category: "doc", type: "TXT", subject: "DBMS", semester: "3" },
    { id: 19, name: "DBMS Unit 3", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 20, name: "DBMS Unit 4", category: "doc", type: "DOC", subject: "DBMS", semester: "3" },
    { id: 21, name: "For Nodel Officer", category: "doc", type: "DOC", subject: "General", semester: "6" },
    { id: 22, name: "Java ActionListener", category: "doc", type: "DOC", subject: "Java", semester: "4" },
    { id: 23, name: "Java Adapter Class", category: "doc", type: "DOC", subject: "Java", semester: "4" },
    { id: 24, name: "Java Layout Manager", category: "doc", type: "DOC", subject: "Java", semester: "4" },
    { id: 25, name: "Operating System OS Question Bank", category: "doc", type: "DOC", subject: "Operating Systems", semester: "4" },
    { id: 26, name: "Web Development CSS Material Final", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 27, name: "Web Development HTML", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 28, name: "Web Development JavaScript Builtin Function Array", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 29, name: "Web Development JavaScript New Material", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 30, name: "Web Development Unit 5", category: "doc", type: "DOC", subject: "Web Development", semester: "5" },
    { id: 31, name: "ASP.NET Image 20250614 WA0000", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 32, name: "ASP.NET Image 20250614 WA0001", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 33, name: "ASP.NET Image 20250614 WA0002", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 34, name: "ASP.NET Image 20250614 WA0003", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 35, name: "ASP.NET Image 20250715 WA0002", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 36, name: "ASP.NET Image 20250715 WA0003", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 37, name: "ASP.NET Image 20250909 WA0000", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 38, name: "ASP.NET Image 20250911 WA0039", category: "image", type: "JPG", subject: "ASP.NET", semester: "6" },
    { id: 39, name: "DBMS WhatsApp Image 2025-03-26 at 7.01.37 AM (1)", category: "image", type: "JPEG", subject: "DBMS", semester: "3" },
    { id: 40, name: "DBMS WhatsApp Image 2025-03-26 at 7.01.37 AM", category: "image", type: "JPEG", subject: "DBMS", semester: "3" },
    { id: 41, name: "Android Syllabus", category: "pdf", type: "PDF", subject: "Android", semester: "6" },
    { id: 42, name: "Android Ripal Pandya", category: "pdf", type: "PDF", subject: "Android", semester: "6" },
    { id: 43, name: "ASP.NET Practical", category: "pdf", type: "PDF", subject: "ASP.NET", semester: "6" },
    { id: 44, name: "C Language Programme File Definition", category: "pdf", type: "PDF", subject: "C Language", semester: "1" },
    { id: 45, name: "C Language HP", category: "pdf", type: "PDF", subject: "C Language", semester: "1" },
    { id: 46, name: "C Language KM", category: "pdf", type: "PDF", subject: "C Language", semester: "1" },
    { id: 47, name: "Cloud Computing Notes", category: "pdf", type: "PDF", subject: "Cloud Computing", semester: "6" },
    { id: 48, name: "Cloud Computing Unit 01", category: "pdf", type: "PDF", subject: "Cloud Computing", semester: "6" },
    { id: 49, name: "Cloud Computing Unit 02", category: "pdf", type: "PDF", subject: "Cloud Computing", semester: "6" },
    { id: 50, name: "Computer Organization and Architecture", category: "pdf", type: "PDF", subject: "Computer Architecture", semester: "3" },
    { id: 51, name: "DBMS 1", category: "pdf", type: "PDF", subject: "DBMS", semester: "3" },
    { id: 52, name: "DBMS 2", category: "pdf", type: "PDF", subject: "DBMS", semester: "3" },
    { id: 53, name: "IKS Ethics Values", category: "pdf", type: "PDF", subject: "IKS", semester: "1" },
    { id: 54, name: "Java JS 2", category: "pdf", type: "PDF", subject: "Java", semester: "4" },
    { id: 55, name: "Java Practical", category: "pdf", type: "PDF", subject: "Java", semester: "4" },
    { id: 56, name: "PHP Practical", category: "pdf", type: "PDF", subject: "PHP", semester: "6" },
    { id: 57, name: "PHP Theory", category: "pdf", type: "PDF", subject: "PHP", semester: "6" },
    { id: 58, name: "Python AI ML Unit 3 Master Upto Topic 3", category: "pdf", type: "PDF", subject: "AI / ML", semester: "6" },
    { id: 59, name: "React JS Semester 6", category: "pdf", type: "PDF", subject: "Web Development", semester: "6" },
    { id: 60, name: "Semester 1 Assignment", category: "pdf", type: "PDF", subject: "General", semester: "1" },
    { id: 61, name: "Semester 1 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "1" },
    { id: 62, name: "Semester 1 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "1" },
    { id: 63, name: "Semester 1 LEB File", category: "pdf", type: "PDF", subject: "General", semester: "1" },
    { id: 64, name: "Semester 2 Assignment", category: "pdf", type: "PDF", subject: "General", semester: "2" },
    { id: 65, name: "Semester 2 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "2" },
    { id: 66, name: "Semester 2 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "2" },
    { id: 67, name: "Semester 3 Assignment", category: "pdf", type: "PDF", subject: "General", semester: "3" },
    { id: 68, name: "Semester 3 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "3" },
    { id: 69, name: "Semester 3 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "3" },
    { id: 70, name: "Semester 4 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "4" },
    { id: 71, name: "Semester 4 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "4" },
    { id: 72, name: "Semester 5 Assignment", category: "pdf", type: "PDF", subject: "General", semester: "5" },
    { id: 73, name: "Semester 5 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "5" },
    { id: 74, name: "Semester 5 Internal Exam", category: "pdf", type: "PDF", subject: "General", semester: "5" },
    { id: 75, name: "Semester 5 LEB File", category: "pdf", type: "PDF", subject: "General", semester: "5" },
    { id: 76, name: "Semester 6 Final Exam", category: "pdf", type: "PDF", subject: "General", semester: "6" },
    { id: 77, name: "Web Development HTML Mayur Sir", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 78, name: "Web Development Chapter 4-5", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 79, name: "Web Development CSS Material", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 80, name: "Web Development FY Exam", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 81, name: "Web Development Microsoft PowerPoint Basics", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 82, name: "Web Development Networking", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 83, name: "Web Development Share Unit 1 Basics of HTML Ripal Pandya", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 84, name: "Web Development Unit 3", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 85, name: "Web Development Word 1", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" },
    { id: 86, name: "Web Development Word Shortcuts", category: "pdf", type: "PDF", subject: "Web Development", semester: "5" }
  ],
 

  quickLinks: [
    { name: "MDN Web Docs", description: "Web platform reference and guides", url: "https://developer.mozilla.org", icon: "book-open" },
    { name: "W3Schools", description: "Quick syntax and examples", url: "https://www.w3schools.com", icon: "graduation-cap" },
    { name: "GeeksforGeeks", description: "DSA and CS fundamentals", url: "https://www.geeksforgeeks.org", icon: "brain" },
    { name: "QuickRef.me", description: "Cheat sheets for everything", url: "https://quickref.me", icon: "zap" },
    { name: "OverAPI", description: "Collected cheat sheets", url: "https://overapi.com", icon: "layout-list" },
    { name: "DevDocs", description: "Offline-first API documentation", url: "https://devdocs.io", icon: "file-code" },
  ],

  discoveries: [
    { title: "Artificial Intelligence", description: "Comprehensive encyclopedia article on AI, machine learning, and neural networks.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Artificial_intelligence", category: "AI" },
    { title: "HTML", description: "The standard markup language for documents designed to be displayed in a web browser.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/HTML", category: "Web Development" },
    { title: "CSS", description: "Style sheet language used for describing the presentation of a document written in HTML.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/CSS", category: "Web Development" },
    { title: "C (Programming Language)", description: "General-purpose, procedural computer programming language supporting structured programming.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/C_(programming_language)", category: "Programming" },
    { title: "C++", description: "General-purpose programming language created as an extension of the C programming language.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/C%2B%2B", category: "Programming" },
    { title: "JavaScript", description: "High-level, interpreted programming language that is a core technology of the World Wide Web.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/JavaScript", category: "Web Development" },
    { title: "JSON", description: "Open standard file format and data interchange format that uses human-readable text.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/JSON", category: "Data Formats" },
    { title: "JQuery", description: "Fast, small, and feature-rich cross-platform JavaScript library.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/JQuery", category: "Web Development" },
    { title: "PHP", description: "General-purpose scripting language especially suited to web development.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/PHP", category: "Backend" },
    { title: "Laravel", description: "Free and open-source PHP web framework for building scalable web applications.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Laravel", category: "Backend" },
    { title: "Python (Programming Language)", description: "High-level, general-purpose programming language emphasizing code readability.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Python_(programming_language)", category: "Programming" },
    { title: "Android (Operating System)", description: "Mobile operating system based on a modified version of the Linux kernel.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Android_(operating_system)", category: "Mobile" },
    { title: "React (Software)", description: "Free and open-source front-end JavaScript library for building user interfaces based on components.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/React_(software)", category: "Web Development" },
    { title: "Node.js", description: "Open-source, cross-platform JavaScript runtime environment built on Chrome's V8 engine.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Node.js", category: "Backend" },
    { title: "ASP.NET", description: "Server-side web framework designed for web development to produce dynamic web pages.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/ASP.NET", category: "Backend" },
    { title: "Oracle Database", description: "Multi-model database management system produced and marketed by Oracle Corporation.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Oracle_Database", category: "Databases" },
    { title: "MySQL", description: "Open-source relational database management system.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/MySQL", category: "Databases" },
    { title: "MongoDB", description: "Source-available cross-platform document-oriented database program classified as NoSQL.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/MongoDB", category: "Databases" },
    { title: "Information Technology", description: "The use of computers to store, retrieve, transmit, and manipulate data or information.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Information_technology", category: "IT" },
    { title: "Cloud Computing", description: "On-demand availability of computer system resources, especially data storage and computing power.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Cloud_computing", category: "IT" },
    { title: "Cybersecurity", description: "The practice of protecting systems, networks, and programs from digital attacks.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Computer_security", category: "IT" },
    { title: "Software Engineering", description: "A systematic approach to the design, development, operation, and maintenance of software.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Software_engineering", category: "IT" },
    { title: "DevOps", description: "A set of practices that combines software development (Dev) and IT operations (Ops).", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/DevOps", category: "IT" },
    { title: "Computer Network", description: "A digital telecommunications network which allows nodes to share resources.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Computer_network", category: "IT" },
    { title: "Data Science", description: "An interdisciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Data_science", category: "IT" },
    { title: "Linux", description: "A family of open-source Unix-like operating systems based on the Linux kernel.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Linux", category: "Operating Systems" },
    { title: "Git", description: "A distributed version control system for tracking changes in source code during software development.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Git", category: "Tools" },
    { title: "API", description: "A connection between computers or between computer programs, standing for Application Programming Interface.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/API", category: "IT" },
    { title: "Java (Programming Language)", description: "A class-based, object-oriented programming language designed for platform independence.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Java_(programming_language)", category: "Programming" },
    { title: "TypeScript", description: "A strict syntactical superset of JavaScript that adds optional static typing.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/TypeScript", category: "Programming" },
    { title: "Ruby (Programming Language)", description: "An interpreted, high-level, general-purpose programming language supporting multiple paradigms.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Ruby_(programming_language)", category: "Programming" },
    { title: "Swift (Programming Language)", description: "A general-purpose, multi-paradigm, compiled programming language developed by Apple.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Swift_(programming_language)", category: "Programming" },
    { title: "Kotlin (Programming Language)", description: "A cross-platform, statically typed, general-purpose programming language with type inference.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Kotlin_(programming_language)", category: "Programming" },
    { title: "Rust (Programming Language)", description: "A multi-paradigm, general-purpose programming language designed for performance and safety.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rust_(programming_language)", category: "Programming" },
    { title: "Go (Programming Language)", description: "A statically typed, compiled programming language designed at Google for concurrency.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Go_(programming_language)", category: "Programming" },
    { title: "SQL", description: "A domain-specific language used in programming for managing data held in relational database management systems.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/SQL", category: "Databases" },
    { title: "Bash (Unix Shell)", description: "A Unix shell and command language written by Brian Fox for the GNU Project.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Bash_(Unix_shell)", category: "Tools" },
    { title: "Assembly Language", description: "Any low-level programming language in which there is a very strong correspondence between the instructions.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Assembly_language", category: "Programming" },
    { title: "R (Programming Language)", description: "A programming language for statistical computing and graphics supported by the R Core Team.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/R_(programming_language)", category: "Data Science" },
    { title: "Scala (Programming Language)", description: "A standard general-purpose programming language providing support for functional programming.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Scala_(programming_language)", category: "Programming" },
    { title: "Perl", description: "A family of two high-level, general-purpose, interpreted, dynamic programming languages.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Perl", category: "Programming" },
    { title: "Lua", description: "A lightweight, high-level, multi-paradigm programming language designed primarily for embedded use.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Lua_(programming_language)", category: "Programming" },
    { title: "Dart (Programming Language)", description: "A client-optimized programming language for apps on multiple platforms developed by Google.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Dart_(programming_language)", category: "Mobile" },
    { title: "Flutter (Software)", description: "An open-source UI software development kit created by Google for cross-platform applications.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Flutter_(software)", category: "Mobile" },
    { title: "Bootstrap (Front-End Framework)", description: "A free and open-source CSS framework directed at responsive, mobile-first front-end web development.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)", category: "Web Development" },
    { title: "Tailwind CSS", description: "A utility-first CSS framework packed with classes that can be composed to build any design.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Tailwind_CSS", category: "Web Development" },
    { title: "Docker (Software)", description: "A set of platform as a service products that use OS-level virtualization to deliver software in packages called containers.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Docker_(software)", category: "IT / DevOps" },
    { title: "Kubernetes", description: "An open-source system for automating deployment, scaling, and management of containerized applications.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Kubernetes", category: "IT / DevOps" },
    { title: "PostgreSQL", description: "A free and open-source relational database management system emphasizing extensibility and SQL compliance.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/PostgreSQL", category: "Databases" },
    { title: "Redis", description: "An open source in-memory data store used as a database, cache, message broker, and stream engine.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Redis", category: "Databases" },
    { title: "Operating System", description: "System software that manages computer hardware, software resources, and provides common services for computer programs.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Operating_system", category: "IT" },
    { title: "Kernel (Operating System)", description: "The core of an operating system that has complete control over everything in the system.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Kernel_(operating_system)", category: "IT" },
    { title: "Compiler", description: "Computer software that translates computer code written in one programming language into another language.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Compiler", category: "Programming" },
    { title: "Interpreter (Computing)", description: "Computer program that directly executes instructions written in a programming or scripting language.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Interpreter_(computing)", category: "Programming" },
    { title: "Algorithm", description: "A finite sequence of rigorous instructions, typically used to solve a class of specific problems or to perform a computation.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Algorithm", category: "Computer Science" },
    { title: "Data Structure", description: "A data organization, management, and storage format that enables efficient access and modification.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Data_structure", category: "Computer Science" },
    { title: "Object-Oriented Programming", description: "A programming paradigm based on the concept of objects, which can contain data and code.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Object-oriented_programming", category: "Programming" },
    { title: "Functional Programming", description: "A programming paradigm where programs are constructed by applying and composing functions.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Functional_programming", category: "Programming" },
    { title: "Version Control", description: "The practice of managing and tracking changes to software code.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Version_control", category: "Tools" },
    { title: "Continuous Integration", description: "The practice of automating the integration of code changes from multiple contributors into a single project.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Continuous_integration", category: "DevOps" },
    { title: "Continuous Delivery", description: "A software engineering approach in which teams produce software in short cycles.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Continuous_delivery", category: "DevOps" },
    { title: "Microservices", description: "An architectural style that structures an application as a collection of services.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Microservices", category: "Architecture" },
    { title: "Web Server", description: "Server software, or hardware dedicated to running said software, that can satisfy client requests on the World Wide Web.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Web_server", category: "Web" },
    { title: "HTTP", description: "An application layer protocol for distributed, collaborative, hypermedia information systems.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol", category: "Web" },
    { title: "HTTPS", description: "An extension of the Hypertext Transfer Protocol for secure communication over a computer network.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/HTTPS", category: "Web" },
    { title: "Transmission Control Protocol", description: "One of the main protocols of the internet protocol suite enabling reliable communication.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Transmission_Control_Protocol", category: "Networking" },
    { title: "Internet Protocol", description: "The principal communications protocol in the Internet protocol suite for relaying datagrams across network boundaries.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Internet_Protocol", category: "Networking" },
    { title: "Domain Name System", description: "A hierarchical and decentralized naming system for computers, services, or other resources connected to the internet.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Domain_Name_System", category: "Networking" },
    { title: "Virtual Private Network", description: "Extends a private network across a public network and enables users to send and receive data securely.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Virtual_private_network", category: "Networking" },
    { title: "Firewall (Computing)", description: "A network security system that monitors and controls incoming and outgoing network traffic.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Firewall_(computing)", category: "Cybersecurity" },
    { title: "Encryption", description: "The process of encoding information so that only authorized parties can access it.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Encryption", category: "Cybersecurity" },
    { title: "Cryptographic Hash Function", description: "A mathematical algorithm that maps data of arbitrary size to a bit array of a fixed size.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Cryptographic_hash_function", category: "Cybersecurity" },
    { title: "Public-Key Cryptography", description: "A cryptographic system that uses pairs of keys: public keys and private keys.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Public-key_cryptography", category: "Cybersecurity" },
    { title: "Software Testing", description: "Investigation conducted to provide stakeholders with information about the quality of the software product under test.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Software_testing", category: "Software Engineering" },
    { title: "Bug (Software)", description: "An error, flaw or fault in a computer program or system that causes it to produce an incorrect or unexpected result.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Software_bug", category: "Software Engineering" },
    { title: "Debugging", description: "The process of identifying and removing errors from computer hardware or software code.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Debugging", category: "Software Engineering" },
    { title: "Integrated Development Environment", description: "A software application that provides comprehensive facilities to computer programmers for software development.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Integrated_development_environment", category: "Tools" },
    { title: "Text Editor", description: "A type of computer program that edits plain text files.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Text_editor", category: "Tools" },
    { title: "Command-Line Interface", description: "A means of interacting with a computer program or operating system where the user issues commands to the program in the form of lines of text.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Command-line_interface", category: "Tools" },
    { title: "Shell Script", description: "A computer program designed to be run by the Unix shell, a command-line interpreter.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Shell_script", category: "Programming" },
    { title: "Regular Expression", description: "A sequence of characters that specifies a search pattern, mainly used for string searching algorithms.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Regular_expression", category: "Computer Science" },
    { title: "XML", description: "A markup language that defines a set of rules for encoding documents in a format that is both human-readable and machine-readable.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/XML", category: "Data Formats" },
    { title: "YAML", description: "A human-readable data serialization language often used for configuration files.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/YAML", category: "Data Formats" },
    { title: "Markdown", description: "A lightweight markup language with plain-text-formatting syntax, designed so that it can be converted to HTML.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Markdown", category: "Data Formats" },
    { title: "WebAssembly", description: "A binary instruction format for a stack-based virtual machine, designed as a portable compilation target for programming languages.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/WebAssembly", category: "Web Development" },
    { title: "Progressive Web App", description: "A type of application software built using web technologies like HTML, CSS, and JavaScript.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Progressive_web_app", category: "Web Development" },
    { title: "Responsive Web Design", description: "An approach to web design that makes web pages render well on a variety of devices and window or screen sizes.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Responsive_web_design", category: "Web Development" },
    { title: "Single-Page Application", description: "A web application or website that interacts with the user by dynamically rewriting the current web page.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Single-page_application", category: "Web Development" },
    { title: "Representational State Transfer", description: "A software architectural style that describes a uniform interface between loosely coupled components in a web service.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Representational_state_transfer", category: "Web Architecture" },
    { title: "GraphQL", description: "An open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/GraphQL", category: "Web Development" },
    { title: "WebSocket", description: "A computer communications protocol, providing full-duplex communication channels over a single TCP connection.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/WebSocket", category: "Networking" },
    { title: "Relational Database", description: "A digital database based on the relational model of data, as proposed by E. F. Codd.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Relational_database", category: "Databases" },
    { title: "NoSQL", description: "Provides a mechanism for storage and retrieval of data that is modeled in means other than the tabular relations.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/NoSQL", category: "Databases" },
    { title: "Distributed Database", description: "A database that is stored across multiple physical locations.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Distributed_database", category: "Databases" },
    { title: "Data Warehouse", description: "A system used for reporting and data analysis, and is considered a core component of business intelligence.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Data_warehouse", category: "Databases" },
    { title: "Big Data", description: "Data sets that are too complex or large for traditional application software to adequately process.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Big_data", category: "Data Science" },
    { title: "Machine Learning", description: "A field of study in artificial intelligence concerned with the development and study of statistical algorithms.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Machine_learning", category: "AI" },
    { title: "Deep Learning", description: "A subset of machine learning based on artificial neural networks with representation learning.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Deep_learning", category: "AI" },
    { title: "Natural Language Processing", description: "A subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Natural_language_processing", category: "AI" },
    { title: "Computer Vision", description: "An interdisciplinary scientific field that deals with how computers can gain high-level understanding from digital images or videos.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Computer_vision", category: "AI" },
    { title: "Neural Network", description: "Computing systems inspired by the biological neural networks that constitute animal brains.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Artificial_neural_network", category: "AI" },
    { title: "Reinforcement Learning", description: "An area of machine learning concerned with how software agents ought to take actions in an environment.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Reinforcement_learning", category: "AI" },
    { title: "Robotics", description: "An interdisciplinary branch of engineering and computer science that involves the design, construction, and operation of robots.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Robotics", category: "Engineering" },
    { title: "Internet of Things", description: "A system of interrelated computing devices, mechanical and digital machines provided with unique identifiers.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Internet_of_things", category: "IT" },
    { title: "Blockchain", description: "A decentralized, distributed and public digital ledger that is used to store records across many computers.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Blockchain", category: "Emerging Tech" },
    { title: "Cryptocurrency", description: "A digital currency designed to work as a medium of exchange through a computer network.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Cryptocurrency", category: "Emerging Tech" },
    { title: "Smart Contract", description: "A computer program or a transaction protocol which is intended to digitally facilitate, verify, or enforce the negotiation of a contract.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Smart_contract", category: "Emerging Tech" },
    { title: "Augmented Reality", description: "An interactive experience of a real-world environment where the objects that reside in the real world are enhanced by computer-generated perceptual information.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Augmented_reality", category: "Emerging Tech" },
    { title: "Virtual Reality", description: "A simulated experience that can be similar to or completely different from the real world.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Virtual_reality", category: "Emerging Tech" },
    { title: "Quantum Computing", description: "A area of study focused on developing computer technology based on the principles of quantum theory.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Quantum_computing", category: "Emerging Tech" },
    { title: "Cyberwarfare", description: "The use of computer technology to disrupt the activities of a state or organization.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Cyberwarfare", category: "Cybersecurity" },
    { title: "Penetration Test", description: "An authorized simulated cyberattack on a computer system, performed to evaluate the security of the system.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Penetration_test", category: "Cybersecurity" },
    { title: "Malware", description: "Any software intentionally designed to cause disruption to a computer, server, client, or computer network.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Malware", category: "Cybersecurity" },
    { title: "Phishing", description: "The fraudulent practice of sending emails purporting to be from reputable companies in order to induce individuals to reveal personal information.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Phishing", category: "Cybersecurity" },
    { title: "Information Security", description: "The practice of protecting information by mitigating information risks, involving prevention or reduction of unauthorized access.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Information_security", category: "Cybersecurity" },
    { title: "Identity Management", description: "A framework of policies and technologies for ensuring that the proper people have the appropriate access to technology resources.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Identity_management", category: "Cybersecurity" },
    { title: "Access Control", description: "In the fields of physical security and information security, access control is the selective restriction of access to a place or other resource.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Access_control", category: "Cybersecurity" },
    { title: "Computer Architecture", description: "In computer engineering, computer architecture is a description of the structure of a computer system made from component parts.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Computer_architecture", category: "Hardware" },
    { title: "Central Processing Unit", description: "The electronic circuitry within a computer that executes instructions comprising a computer program.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Central_processing_unit", category: "Hardware" },
    { title: "Graphics Processing Unit", description: "A specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Graphics_processing_unit", category: "Hardware" },
    { title: "Random-Access Memory", description: "A form of computer data storage that stores data and machine code currently being used.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Random-access_memory", category: "Hardware" },
    { title: "Solid-State Drive", description: "A solid-state storage device that uses integrated circuit assemblies to store data persistently.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Solid-state_drive", category: "Hardware" },
    { title: "Hard Disk Drive", description: "An electro-mechanical data storage device that stores and retrieves digital data using magnetic storage.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hard_disk_drive", category: "Hardware" },
    { title: "Motherboard", description: "The main printed circuit board in general-purpose computers and other expandable systems.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Motherboard", category: "Hardware" },
    { title: "Power Supply Unit", description: "Converts mains AC to low-voltage regulated DC power for the internal components of a computer.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Power_supply_unit_(computer)", category: "Hardware" },
    { title: "Network Interface Controller", description: "A computer hardware component that connects a computer to a computer network.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Network_interface_controller", category: "Hardware" },
    { title: "Router (Computing)", description: "A device that connects two or more packet-switched networks or subnetworks.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Router_(computing)", category: "Hardware" },
    { title: "Switch (Network)", description: "A computer networking device that connects devices together on a computer network by using packet switching.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Network_switch", category: "Hardware" },
    { title: "Modem", description: "A hardware device that converts data into a format suitable for a transmission medium so that it can be transmitted easily.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Modem", category: "Hardware" },
    { title: "Server (Computing)", description: "A piece of computer hardware or software that provides functionality for other programs or devices.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Server_(computing)", category: "Hardware" },
    { title: "Supercomputer", description: "A computer with a high level of performance compared to a general-purpose computer.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Supercomputer", category: "Hardware" },
    { title: "Embedded System", description: "A computer system with a dedicated function within a larger mechanical or electrical system.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Embedded_system", category: "Hardware" },
    { title: "Microcontroller", description: "A compact integrated circuit designed to govern a specific operation in an embedded system.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Microcontroller", category: "Hardware" },
    { title: "Logic Gate", description: "An idealized or physical device implementing a Boolean function; a logical operation performed on one or more binary inputs.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Logic_gate", category: "Hardware" },
    { title: "Binary Number", description: "A number expressed in the base-2 numeral system or binary numeral system, which uses only two symbols: typically 0 and 1.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Binary_number", category: "Computer Science" },
    { title: "Boolean Algebra", description: "The branch of algebra in which the values of the variables are the truth values true and false.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Boolean_algebra", category: "Computer Science" },
    { title: "Automata Theory", description: "The study of abstract machines and automata, as well as the computational problems that can be solved using them.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Automata_theory", category: "Computer Science" },
    { title: "Turing Machine", description: "A mathematical model of computation that defines an abstract machine that manipulates symbols on a strip of tape.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Turing_machine", category: "Computer Science" },
    { title: "Computability Theory", description: "A branch of mathematical logic and computer science that originates in the 1930s with the study of computable functions.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Computability_theory", category: "Computer Science" },
    { title: "Computational Complexity Theory", description: "A branch of the theory of computation in computer science that focuses on classifying computational problems according to their inherent difficulty.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Computational_complexity_theory", category: "Computer Science" },
    { title: "Graph Theory", description: "The study of graphs, which are mathematical structures used to model pairwise relations between objects.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Graph_theory", category: "Computer Science" },
    { title: "Sorting Algorithm", description: "An algorithm that puts elements of a list in a certain order.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Sorting_algorithm", category: "Computer Science" },
    { title: "Searching Algorithm", description: "Any algorithm designed to solve a search problem, retrieving stored data from a data structure.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Search_algorithm", category: "Computer Science" },
    { title: "Dynamic Programming", description: "A method for solving a complex problem by breaking it down into a collection of simpler subproblems.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Dynamic_programming", category: "Computer Science" },
    { title: "Greedy Algorithm", description: "An algorithmic paradigm that builds up a solution piece by piece, always choosing the next piece that offers the most obvious and immediate benefit.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Greedy_algorithm", category: "Computer Science" },
    { title: "Recursion", description: "The process in which a function calls itself directly or indirectly.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Recursion_(computer_science)", category: "Computer Science" },
    { title: "Hash Table", description: "A data structure that implements an associative array abstract data type, a structure that can map keys to values.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hash_table", category: "Computer Science" },
    { title: "Binary Tree", description: "A hierarchical data structure in which each node has at most two children.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Binary_tree", category: "Computer Science" },
    { title: "Linked List", description: "A linear collection of data elements whose order is not given by their physical placement in memory.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Linked_list", category: "Computer Science" },
    { title: "Stack (Abstract Data Type)", description: "An abstract data type that serves as a collection of elements, with two principal operations: push and pop.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Stack_(abstract_data_type)", category: "Computer Science" },
    { title: "Queue (Abstract Data Type)", description: "A particular kind of abstract data type or collection in which the entities in the collection are kept in order.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Queue_(abstract_data_type)", category: "Computer Science" },
    { title: "Heap (Data Structure)", description: "A specialized tree-based data structure which is essentially an almost complete tree that satisfies the heap property.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Heap_(data_structure)", category: "Computer Science" },
    { title: "Trie", description: "A type of search tree, a tree data structure used for locating specific keys from within a set.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Trie", category: "Computer Science" },
    { title: "Software Design Pattern", description: "A general, reusable solution to a commonly occurring problem within a given context in software design.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Software_design_pattern", category: "Software Engineering" },
    { title: "Model–View–Controller", description: "A software architectural pattern commonly used for developing user interfaces that divide the related program logic.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller", category: "Software Engineering" },
    { title: "Agile Software Development", description: "An approach to software development under which requirements and solutions evolve through the collaborative effort of self-organizing and cross-functional teams.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Agile_software_development", category: "Software Engineering" },
    { title: "Scrum (Software Development)", description: "An agile framework for developing, delivering, and sustaining complex products.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Scrum_(software_development)", category: "Software Engineering" },
    { title: "Waterfall Model", description: "A breakdown of project activities into linear sequential phases, where each phase depends on the deliverables of the previous one.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Waterfall_model", category: "Software Engineering" },
    { title: "Test-Driven Development", description: "A software development process relying on software requirements being converted to test cases before software is fully developed.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Test-driven_development", category: "Software Engineering" },
    { title: "Code Refactoring", description: "The process of restructuring existing computer code without changing its external behavior.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Code_refactoring", category: "Software Engineering" },
    { title: "Technical Debt", description: "A concept in software development that reflects the implied cost of additional rework caused by choosing an easy solution now instead of using a better approach.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Technical_debt", category: "Software Engineering" },
    { title: "Open-Source Software", description: "Computer software that is released under a license in which the copyright holder grants users the rights to use, study, change, and distribute the software.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Open-source_software", category: "Software" },
    { title: "Proprietary Software", description: "Computer software for which the software's publisher or another person retains intellectual property rights.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Proprietary_software", category: "Software" },
    { title: "Shareware", description: "Proprietary software that is provided to users without payment on a trial basis.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Shareware", category: "Software" },
    { title: "Freeware", description: "Proprietary software that is available for use at zero cost or for an optional donation.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Freeware", category: "Software" },
    { title: "Free Software", description: "Software that grants users freedom to run, copy, distribute, study, change and improve the software.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Free_software", category: "Software" },
    { title: "Software License", description: "A legal instrument governing the use or redistribution of software.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Software_license", category: "Software" },
    { title: "Copyright", description: "A type of intellectual property that grants its owner the exclusive right to copy and distribute a creative work.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Copyright", category: "Legal" },
    { title: "Patent", description: "A type of intellectual property that gives its owner the legal right to exclude others from making, using, or selling an invention.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Patent", category: "Legal" },
    { title: "Trade Secret", description: "A practice, design, formula, process, design, instrument, pattern, or compilation of information which is not generally known.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Trade_secret", category: "Legal" },
    { title: "Information Technology Infrastructure Library", description: "A set of detailed practices for IT service management focused on aligning IT services with the needs of business.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Information_Technology_Infrastructure_Library", category: "IT Service Management" },
    { title: "Enterprise Resource Planning", description: "The integrated management of main business processes, often in real time and mediated by software and technology.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Enterprise_resource_planning", category: "Business IT" },
    { title: "Customer Relationship Management", description: "A technology for managing all your company's relationships and interactions with customers and potential customers.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Customer_relationship_management", category: "Business IT" },
    { title: "Content Management System", description: "Computer software used to manage the creation and modification of digital content.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Content_management_system", category: "Web" },
    { title: "WordPress", description: "A free and open-source content management system written in PHP and paired with a database.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/WordPress", category: "Web" },
    { title: "Virtualization", description: "The act of creating a virtual rather than actual version of something, such as hardware platforms, storage devices, and computer network resources.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Virtualization", category: "IT / DevOps" },
    { title: "Hypervisor", description: "Computer software, firmware or hardware that creates and runs virtual machines.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hypervisor", category: "IT / DevOps" },
    { title: "Containerization", description: "An OS-level virtualization method used to deploy and run applications without launching a whole virtual machine for each app.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/OS-level_virtualization", category: "IT / DevOps" },
    { title: "Infrastructure as Code", description: "The process of managing and provisioning computer data centers through machine-readable definition files.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Infrastructure_as_code", category: "IT / DevOps" },
    { title: "Serverless Computing", description: "A cloud computing execution model in which the cloud provider allocates machine resources on-demand.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Serverless_computing", category: "Cloud Computing" },
    { title: "Edge Computing", description: "A distributed computing paradigm that brings computation and data storage closer to the sources of data.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Edge_computing", category: "Cloud Computing" },
    { title: "Fog Computing", description: "An architecture that uses one or a collaborative multitude of end-user or near-user edge devices to carry out a substantial amount of storage, communication, and control.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Fog_computing", category: "Cloud Computing" },
    { title: "Grid Computing", description: "The use of widely distributed computer resources to reach a common goal.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grid_computing", category: "Cloud Computing" },
    { title: "Distributed Computing", description: "A field of computer science that studies distributed systems.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Distributed_computing", category: "Computer Science" },
    { title: "Peer-to-Peer", description: "A decentralized communications model in which each party has the same capabilities and either party can initiate a communication session.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Peer-to-peer", category: "Networking" },
    { title: "Client–Server Model", description: "A distributed application structure that partitions tasks or workloads between the providers of a resource or service.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Client%E2%80%93server_model", category: "Networking" },
    { title: "Load Balancing", description: "The process of distributing a set of tasks over a set of resources, with the aim of making their overall processing more efficient.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Load_balancing_(computing)", category: "Networking" },
    { title: "Content Delivery Network", description: "A geographically distributed network of proxy servers and their data centers.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Content_delivery_network", category: "Networking" },
    { title: "Packet Switching", description: "A method of grouping data transmitted over a digital network into packets.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Packet_switching", category: "Networking" },
    { title: "Circuit Switching", description: "A methodology in which a communication session is established before any data can be transferred.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Circuit_switching", category: "Networking" },
    { title: "OSI Model", description: "A conceptual model that provides a standard for different computer systems to be able to communicate within a network.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/OSI_model", category: "Networking" },
    { title: "TCP/IP Model", description: "A concise version of the OSI model, serving as the communications architecture for the Internet.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Internet_protocol_suite", category: "Networking" },
    { title: "MAC Address", description: "A unique identifier assigned to a network interface controller for use as a network address in communications.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/MAC_address", category: "Networking" },
    { title: "IP Address", description: "A numerical label assigned to each device connected to a computer network that uses the Internet Protocol for communication.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/IP_address", category: "Networking" },
    { title: "Port (Computer Networking)", description: "A communication endpoint in computer networking.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Port_(computer_networking)", category: "Networking" },
    { title: "Web Scraping", description: "Data scraping used for extracting data from websites.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Web_scraping", category: "Data Science" },
    { title: "Data Mining", description: "A process of discovering patterns in large data sets involving methods at the intersection of machine learning, statistics, and database systems.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Data_mining", category: "Data Science" },
    { title: "Business Intelligence", description: "Technology-driven processes and tools for analyzing data and delivering actionable information.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Business_intelligence", category: "Data Science" },
    { title: "Data Visualization", description: "The graphical representation of information and data.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Data_visualization", category: "Data Science" },
    { title: "Big Data Analytics", description: "The often complex process of examining big data to uncover information.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Big_data_analytics", category: "Data Science" },
    { title: "Predictive Analytics", description: "Encompasses a variety of statistical techniques from data mining, predictive modeling, and machine learning.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Predictive_analytics", category: "Data Science" },
    { title: "Natural Language Understanding", description: "A subtopic of natural language processing in artificial intelligence that deals with machine reading comprehension.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Natural-language_understanding", category: "AI" },
    { title: "Speech Recognition", description: "An interdisciplinary subfield of computer science and computational linguistics that develops methodologies and technologies.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Speech_recognition", category: "AI" },
    { title: "Expert System", description: "In artificial intelligence, an expert system is a computer system that emulates the decision-making ability of a human expert.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Expert_system", category: "AI" },
    { title: "Knowledge Representation and Reasoning", description: "The field of artificial intelligence dedicated to representing information about the world in a form that a computer system can use.", source: "Wikipedia", url: "https://en.wikipedia.org/wiki/Knowledge_representation_and_reasoning", category: "AI" }
  ],
  activities: [
    { text: "New resource added to DBMS", time: "2h ago" },
    { text: "Nexora project updated", time: "6h ago" },
    { text: "Library reorganized — 87 files", time: "2d ago" },
    { text: "New discovery: Explorable Explanations", time: "3d ago" },
    { text: "System maintenance completed", time: "5d ago" },
  ],

  stats: {
    visitors: 1248,
    projects: 6,
    documents: 115,
    version: "v8.0",
  },

  notice: {
    active: true,
    title: "System Notice",
    text: "We are actively improving this web & app. Stay tuned for new updates.",
  },
};
